devops/ansible/roles/web_app/tasks/main.yml

Maxim Kozhinov lab6
Latest commit 1916b97 on Oct 11
 History
 0 contributors
28 lines (23 sloc)  636 Bytes

---
- name: Wipe everything
 ansible.builtin.import_tasks: 0-wipe.yml
 when: web_app_full_wipe | bool
 tags: ["web_app", "web_app_wipe"]

- name: Start of web_app
 block:

  - name: Dir creation
    ansible.builtin.file:
      path: "{{ web_app_dir }}"
      state: directory
      mode: '0700'

  - name: Docker compose file template
    ansible.builtin.template:
      src: "docker-compose.yml.j2"
      dest: "{{ web_app_dir }}/docker-compose.yml"
      mode: "0600"

  - name: Docker compose start
    community.docker.docker_compose:
      project_src: "{{ web_app_dir }}"
      state: present
      pull: true

  tags: ["web_app"]
