apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-deployment
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: node-app-{{ .Release.Name }}
  template:
    metadata:
      labels:
        app:  node-app-{{ .Release.Name }}
    spec:
      containers:
        - name: node-app-container-{{.Release.Name}}
          image: {{ .Values.container.image }}
          env:
            - name: MY_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: credentials
                  key: password
          volumeMounts:
            - name: config-volume
              mountPath: "/usr/src/app/config"
          ports:
            - containerPort: {{ .Values.container.port }}
      volumes:
        - name: config-volume
          configMap:
            name: cm
