container:
  image: afonya2001/devops
  port: 8080

resources:
  limits:
    cpu: 2.0
    memory: 256Mi
  requests:
    cpu: 1.0
    memory: 128Mi

prometheus:
  additionalServiceMonitors:
    - name: node-app-service-monitor
      selector:
        matchLabels:
          app.kubernetes.io/instance: node-app
          app.kubernetes.io/name: node-app-chart
      endpoints:
        - port: http
          interval: 10s
          path: /metrics

replicaCount: 3

volumes:
  config:
    name: config-volume
    mountPath: /app/config.json
    subPath: config.json

  persistent:
    name: persistent-volume
    mountPath: /app/storage
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClass: ""
      resources:
        requests:
          storage: 128Mi