web_app_name: "node_app"
web_app_image_name: "node_applatest"
web_app_image: afonyaa/{{ web_app_image_name }}
web_app_ports: "8080:8080"
web_app_full_wipe: false
web_app_dir: "/opt/devops/{{ web_app_name }}"